// Datos derivados de PAO_seguimiento.xlsx (hoja PAO_Seguimiento), fila CTs excluida a pedido del usuario.
// stage_* : 'X' completada | 'N/C' no corresponde | null pendiente

const X = 'X';
const NC = 'N/C';

const USERS = [
  { name: 'Alessandro', email: 'alecoronadosiles@hotmail.com', role: 'admin' },
  { name: 'VP', email: '', role: 'editor' },
  { name: 'Gastón', email: '', role: 'viewer' },
  { name: 'Javier', email: '', role: 'viewer' },
  { name: 'Eliana', email: '', role: 'viewer' },
];

const FECHA_REPORTE = '2026-05-30';

const PROJECTS = [
  { garantia:'Soberano', codigo:'AR-XXX', pais:'ARGENTINA', apodo:'FPI - VIALIDAD', prioridad:1,
    stages:[null,null,null,null,null,null,null,null], estado:'SIN CARTA CONSULTA', probabilidad:'A',
    monto_total:200, aprob:[100,100,0,0], monto_aprobado:0, desem:[75,0,0,0] },
  { garantia:'Soberano', codigo:'AR-XXX', pais:'ARGENTINA', apodo:'CANJE DE DEUDA (RIGI)', prioridad:1,
    stages:[null,null,null,null,null,null,null,null], estado:'SIN CARTA CONSULTA', probabilidad:'A',
    monto_total:250, aprob:[250,0,0,0], monto_aprobado:0, desem:[0,0,0,0] },
  { garantia:'Soberano', codigo:'AR-XXX', pais:'ARGENTINA', apodo:'ULTIMA MILLA MISIONES', prioridad:1,
    stages:[X,null,null,null,null,null,null,null], estado:'CON CARTA CONSULTA', probabilidad:'B',
    monto_total:42, aprob:[21,0,21,0], monto_aprobado:0, desem:[0,0,0,0] },
  { garantia:'Soberano', codigo:'AR-XXX', pais:'ARGENTINA', apodo:'RUTA 13 (TRAMO 3 Y 4) - CHACO', prioridad:1,
    stages:[X,X,X,X,X,X,X,X], estado:'CON CARTA CONSULTA', probabilidad:'A',
    monto_total:120, aprob:[60,0,60,0], monto_aprobado:0, desem:[0,0,0,0] },
  { garantia:'Soberano', codigo:'AR-XXX', pais:'ARGENTINA', apodo:'CAMINOS RURALES/SALUD - JUJUY', prioridad:1,
    stages:[X,null,null,null,null,null,null,null], estado:'SIN CARTA CONSULTA', probabilidad:'B',
    monto_total:100, aprob:[30,0,35,35], monto_aprobado:0, desem:[0,0,0,0] },
  { garantia:'Soberano', codigo:'BO-XXX', pais:'BOLIVIA', apodo:'MANT. RED VIAL FUNDAMENTAL', prioridad:1,
    stages:[null,null,null,null,null,null,null,null], estado:'CON CARTA CONSULTA', probabilidad:'A',
    monto_total:75, aprob:[75,0,0,0], monto_aprobado:0, desem:[0,0,0,0] },
  { garantia:'Soberano', codigo:'BR-160', pais:'BRASIL', apodo:'SERGIPE', prioridad:1,
    stages:[X,X,X,X,X,X,null,X], estado:'CON CARTA CONSULTA', probabilidad:'A',
    monto_total:78, aprob:[78,0,0,0], monto_aprobado:0, desem:[0,0,0,0] },
  { garantia:'Soberano', codigo:'BR-164', pais:'BRASIL', apodo:'ALAGOINHA', prioridad:1,
    stages:[X,X,X,X,X,X,null,null], estado:'CON CARTA CONSULTA', probabilidad:'A',
    monto_total:30, aprob:[30,0,0,0], monto_aprobado:0, desem:[0,0,0,0] },
  { garantia:'Soberano', codigo:'BR-165', pais:'BRASIL', apodo:'JABOTAO', prioridad:1,
    stages:[X,X,X,X,null,null,null,null], estado:'CON CARTA CONSULTA', probabilidad:'A',
    monto_total:52, aprob:[52,0,0,0], monto_aprobado:0, desem:[0,0,0,0] },
  { garantia:'Soberano', codigo:'BR-163', pais:'BRASIL', apodo:'CAMBORI', prioridad:1,
    stages:[X,X,X,X,X,X,null,null], estado:'CON CARTA CONSULTA', probabilidad:'A',
    monto_total:30, aprob:[30,0,0,0], monto_aprobado:0, desem:[0,0,0,0] },
  { garantia:'Soberano', codigo:'BR-167', pais:'BRASIL', apodo:'JOINVILLE III', prioridad:1,
    stages:[X,X,X,X,X,X,null,null], estado:'CON CARTA CONSULTA', probabilidad:'A',
    monto_total:35, aprob:[35,0,0,0], monto_aprobado:0, desem:[0,0,0,0] },
  { garantia:'Soberano', codigo:'BR-168', pais:'BRASIL', apodo:'PETROLINA II', prioridad:1,
    stages:[X,X,X,X,null,null,null,null], estado:'CON CARTA CONSULTA', probabilidad:'A',
    monto_total:60, aprob:[60,0,0,0], monto_aprobado:0, desem:[0,0,0,0] },
  { garantia:'Soberano', codigo:'BR-166', pais:'BRASIL', apodo:'NATAL', prioridad:1,
    stages:[X,X,X,X,null,null,null,null], estado:'CON CARTA CONSULTA', probabilidad:'C',
    monto_total:19.1, aprob:[19.1,0,0,0], monto_aprobado:0, desem:[0,0,0,0] },
  { garantia:'Soberano', codigo:'PAR-28#2', pais:'PARAGUAY', apodo:'BIOCEÁNICA - Etapa II', prioridad:1,
    stages:[X,X,X,X,X,X,X,X], estado:'SEGUNDA ETAPA', probabilidad:'B',
    monto_total:110, aprob:[110,0,0,0], monto_aprobado:110, desem:[0,0,0,0] },
  { garantia:'Soberano', codigo:'URU-27#2', pais:'URUGUAY', apodo:'SANEAMIENTO MALDONADO - Etapa II', prioridad:1,
    stages:[NC,NC,NC,NC,NC,NC,NC,NC], estado:'SEGUNDA ETAPA', probabilidad:'A',
    monto_total:23, aprob:[23,14.9,5.9,0], monto_aprobado:0, desem:[0,18,15,0] },
  { garantia:'Soberano', codigo:'URU-25#2', pais:'URUGUAY', apodo:'SANEAMIENTO DEL INTERIOR - Etapa II', prioridad:1,
    stages:[NC,NC,NC,NC,NC,NC,NC,NC], estado:'SEGUNDA ETAPA', probabilidad:'A',
    monto_total:70, aprob:[30,30,40,40], monto_aprobado:0, desem:[0,35,35,0] },
  { garantia:'Soberano', codigo:'URU-26-2', pais:'URUGUAY', apodo:'CAJA BANCARIA', prioridad:1,
    stages:[NC,NC,NC,NC,NC,NC,NC,NC], estado:'SEGUNDA ETAPA', probabilidad:'A',
    monto_total:25, aprob:[25,0,0,0], monto_aprobado:0, desem:[0,0,0,0] },
  { garantia:'Soberano', codigo:'UR-XXX', pais:'URUGUAY', apodo:'FPI BONO ESCOLAR', prioridad:1,
    stages:[X,null,null,null,null,null,null,null], estado:'SIN CARTA CONSULTA', probabilidad:'A',
    monto_total:70, aprob:[13,15,25,17], monto_aprobado:0, desem:[13,15,25,0] },
  { garantia:'Soberano', codigo:'UR-XXX', pais:'URUGUAY', apodo:'PPI URUGUAY', prioridad:1,
    stages:[X,null,null,null,null,null,null,null], estado:'SIN CARTA CONSULTA', probabilidad:'A',
    monto_total:235, aprob:[235,0,0,0], monto_aprobado:0, desem:[235,0,0,0] },
  { garantia:'Soberano', codigo:'UR-XXX', pais:'URUGUAY', apodo:'FPI URUGUAY (Infraestructura Vial)', prioridad:1,
    stages:[X,null,null,null,null,null,null,null], estado:'SIN CARTA CONSULTA', probabilidad:'A',
    monto_total:300, aprob:[90,110,100,0], monto_aprobado:0, desem:[90,110,100,0] },
  { garantia:'No Soberano', codigo:'GNS-BR-XXX', pais:'GNS', apodo:'BADESC', prioridad:1,
    stages:[X,X,X,X,X,X,X,X], estado:'APROBADO', probabilidad:'A',
    monto_total:55, aprob:[55,0,0,0], monto_aprobado:55, desem:[0,0,0,0] },
  { garantia:'No Soberano', codigo:'GNS-BR-XXX', pais:'GNS', apodo:'BDMG', prioridad:1,
    stages:[X,X,X,X,X,X,X,X], estado:'APROBADO', probabilidad:'A',
    monto_total:30, aprob:[30,0,0,0], monto_aprobado:30, desem:[0,0,0,0] },
  { garantia:'No Soberano', codigo:'GNS-PY-XXX', pais:'GNS', apodo:'AFD', prioridad:1,
    stages:[X,null,null,null,null,null,null,null], estado:'CON CARTA CONSULTA', probabilidad:'B',
    monto_total:55, aprob:[55,0,0,0], monto_aprobado:0, desem:[55,0,0,0] },
  { garantia:'No Soberano', codigo:'GNS-PY-XXX', pais:'GNS', apodo:'SAAE ATIBAIA', prioridad:1,
    stages:[null,null,null,null,null,null,null,null], estado:'CON CARTA CONSULTA', probabilidad:'B',
    monto_total:30, aprob:[0,30,0,0], monto_aprobado:0, desem:[30,0,0,0] },
].map(p => ({ ...p, fecha_reporte: FECHA_REPORTE }));

module.exports = { USERS, PROJECTS };
